services:
  postgres:
    image: postgres:16
    container_name: crm_database
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: crm_usuarios
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/perfil_usuarios.csv:/docker-entrypoint-initdb.d/perfil_usuarios.csv
  ml-service:
    build:
      context: ./ml-service
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - modelos:/app/models      
    depends_on:
      - postgres
  dashboard:
    build:
      context: ./dashboards
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data  
      - modelos:/app/models          
    depends_on:
      - ml-service
volumes:
  modelos: